name: test
on: [push, pull_request]
jobs:
  compile:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
	uses: actions/checkout@v3
      - name: Setup Arduino CLI
	uses: arduino/setup-arduino-cli@v1
      - name: Install platform
	run: |
	  arduino-cli core update-index
	  arduino-cli core install esp32:esp32
      - name: lint
	uses: arduino/arduino-lint-action@v1
	with: 
	  compliance: strict
      - name: Compile Sketch
	run: arduino-cli compile --fqbn esp32:esp32:esp32s2
