name: build
on: [push, pull_request]
jobs:
  compile:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-arduino-cli@v1
      - run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli lib install AutoConnect
      - run: cd test152; arduino-cli compile --fqbn esp32:esp32:esp32s2 --output-dir build
      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
          name: test152.ino.bin
          path: |
            test152/build/*.ino.bin
            
