name: test
on: [push, pull_request]
jobs:
  compile:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-arduino-cli@v1
      - run: |
	  arduino-cli core update-index
	  arduino-cli core install esp32:esp32
      - uses: arduino/arduino-lint-action@v1
	with: 
	  compliance: strict
      - run: arduino-cli compile --fqbn esp32:esp32:esp32s2
